# Generated by Django 6.0.2 on 2026-02-08 14:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='介绍')),
            ],
            options={
                'verbose_name': '需求调查报告列表页',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('procurement_name', models.TextField(verbose_name='拟采购名称')),
                ('analysis_type', models.CharField(default='一键分析', max_length=50, verbose_name='分析编报')),
                ('analysis_time', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('category', models.CharField(choices=[('default', '默认'), ('analysis', '调查分析'), ('ai', '人工智能'), ('bigdata', '大数据'), ('scope', '中成氏范围'), ('opinion', '舆论研究'), ('iot', '物联'), ('life', '生活')], default='default', max_length=20, verbose_name='分类')),
                ('summary', wagtail.fields.RichTextField(blank=True, verbose_name='报告摘要')),
                ('content', wagtail.fields.RichTextField(blank=True, verbose_name='报告内容')),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/pdfs/', verbose_name='PDF文件')),
            ],
            options={
                'verbose_name': '需求调查报告',
            },
            bases=('wagtailcore.page',),
        ),
    ]
