# Generated by Django 6.0.2 on 2026-02-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpage',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='reportpage',
            name='analysis_type',
            field=models.CharField(choices=[('一键分析', '一键分析'), ('高级分析', '高级分析')], default='一键分析', max_length=50, verbose_name='选择制度'),
        ),
    ]
