# Generated by Django 6.0.2 on 2026-02-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportpage_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpage',
            name='ai_summary_analysis',
            field=models.TextField(blank=True, verbose_name='AI总结分析'),
        ),
        migrations.AddField(
            model_name='reportpage',
            name='market_supply_analysis',
            field=models.TextField(blank=True, verbose_name='市场供给分析'),
        ),
        migrations.AddField(
            model_name='reportpage',
            name='market_trend_analysis',
            field=models.TextField(blank=True, verbose_name='市场交易趋势'),
        ),
    ]
