# Generated by Django 6.0.2 on 2026-02-12 16:09

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportpage_ai_summary_analysis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('procurement_method', models.CharField(max_length=100, verbose_name='采购方式')),
                ('procurement_time', models.DateField(verbose_name='采购时间')),
                ('procurement_unit', models.CharField(max_length=255, verbose_name='采购单位')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='预算(万元)')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='供应商名称')),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='成交(万元)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_projects', to='reports.reportpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
