# Generated by Django 6.0.2 on 2026-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_historicalproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='预算(万元)'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='procurement_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='采购方式'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='procurement_time',
            field=models.DateField(blank=True, null=True, verbose_name='采购时间'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='procurement_unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='采购单位'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商名称'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='成交(万元)'),
        ),
    ]
