# Generated by Django 6.0.2 on 2026-02-12 17:28

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_historicalproject_budget_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OngoingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='项目名称')),
                ('bid_opening_time', models.DateField(blank=True, null=True, verbose_name='开标时间')),
                ('procurement_unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='采购单位')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='预算(万元)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ongoing_projects', to='reports.reportpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
