# Generated by Django 6.0.2 on 2026-02-14 08:47

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_ongoingproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseIntention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='预算(万元)')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='区域')),
                ('procurement_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='采购品目')),
                ('procurement_unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='采购单位')),
                ('publish_time', models.DateField(blank=True, null=True, verbose_name='发布时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='采购内容')),
                ('detail_url', models.URLField(blank=True, null=True, verbose_name='详情链接')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_intentions', to='reports.reportpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
