# Generated by Django 6.0.2 on 2026-02-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_purchaseintention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseintention',
            name='region',
        ),
        migrations.AddField(
            model_name='purchaseintention',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='purchaseintention',
            name='province',
            field=models.CharField(choices=[('全国', '全国'), ('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆'), ('香港', '香港'), ('澳门', '澳门'), ('台湾', '台湾')], default='全国', max_length=50, verbose_name='地区（省份）'),
        ),
    ]
