# Generated by Django 6.0.2 on 2026-02-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_purchaseintention_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='detail_link',
            field=models.URLField(blank=True, null=True, verbose_name='详情链接'),
        ),
        migrations.AddField(
            model_name='ongoingproject',
            name='detail_link',
            field=models.URLField(blank=True, null=True, verbose_name='详情链接'),
        ),
    ]
