# Generated by Django 6.0.2 on 2026-02-15 14:32

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_reportannouncement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='合同名称')),
                ('url', models.URLField(blank=True, null=True, verbose_name='详情链接')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布时间')),
                ('region', models.CharField(choices=[('全国', '全国'), ('北京', '北京'), ('天津', '天津'), ('河北', '河北'), ('山西', '山西'), ('内蒙古', '内蒙古'), ('辽宁', '辽宁'), ('吉林', '吉林'), ('黑龙江', '黑龙江'), ('上海', '上海'), ('江苏', '江苏'), ('浙江', '浙江'), ('安徽', '安徽'), ('福建', '福建'), ('江西', '江西'), ('山东', '山东'), ('河南', '河南'), ('湖北', '湖北'), ('湖南', '湖南'), ('广东', '广东'), ('广西', '广西'), ('海南', '海南'), ('重庆', '重庆'), ('四川', '四川'), ('贵州', '贵州'), ('云南', '云南'), ('西藏', '西藏'), ('陕西', '陕西'), ('甘肃', '甘肃'), ('青海', '青海'), ('宁夏', '宁夏'), ('新疆', '新疆'), ('香港', '香港'), ('澳门', '澳门'), ('台湾', '台湾')], default='全国', max_length=50, verbose_name='地区')),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='预算金额(万元)')),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='成交金额(万元)')),
                ('buyer', models.CharField(blank=True, max_length=255, null=True, verbose_name='采购单位')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_contracts', to='reports.reportpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
