# Generated by Django 6.0.2 on 2026-02-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_reportcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcontract',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='城市'),
        ),
    ]
