# Generated by Django 6.0.2 on 2026-02-15 14:49

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_reportcontract_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportBiddingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='文件标题')),
                ('source', models.CharField(default='山东政府采购网', max_length=100, verbose_name='来源')),
                ('upload_time', models.DateField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('file', models.FileField(upload_to='reports/documents/', verbose_name='文件')),
                ('doc_type', models.CharField(choices=[('procurement', '采购文件'), ('contract', '合同文件'), ('acceptance', '验收文件'), ('other', '其他文件')], default='procurement', max_length=50, verbose_name='文件类型')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_documents', to='reports.reportpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
