# Generated by Django 6.0.2 on 2026-02-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_reportbiddingdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbiddingdocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='文件标题'),
        ),
    ]
