# Generated by Django 6.0.2 on 2026-02-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_reportbiddingdocument_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbiddingdocument',
            name='source',
            field=models.CharField(blank=True, default='山东政府采购网', max_length=100, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='reportbiddingdocument',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='文件标题'),
        ),
    ]
