# Generated by Django 6.0.2 on 2026-02-15 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_reportbiddingdocument_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbiddingdocument',
            name='upload_time',
            field=models.DateField(default=datetime.date.today, verbose_name='上传时间'),
        ),
    ]
