# Generated by Django 6.0.2 on 2026-02-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_alter_reportbiddingdocument_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportbiddingdocument',
            name='file',
            field=models.FileField(blank=True, upload_to='reports/documents/', verbose_name='文件'),
        ),
    ]
