# Generated by Django 6.0.2 on 2026-02-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_alter_reportbiddingdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpage',
            name='is_public',
            field=models.BooleanField(default=False, help_text='勾选后所有用户都能看到此报告（管理员修改后所有人同步更新）', verbose_name='公共报告'),
        ),
    ]
