# Generated by Django 6.0.2 on 2026-02-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '首页'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_subtitle',
            field=models.CharField(blank=True, default='让采购更简单', max_length=200, verbose_name='横幅副标题'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='招投标大数据', max_length=200, verbose_name='横幅标题'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='search_placeholder',
            field=models.CharField(default='请输入关键字搜索...', max_length=100, verbose_name='搜索框提示文字'),
        ),
    ]
