# Generated by Django 6.0.2 on 2026-02-08 14:23

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='介绍')),
            ],
            options={
                'verbose_name': '公告列表页',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AnnouncementPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('announcement_type', models.CharField(choices=[('bidding', '招标公告'), ('change', '变更公告'), ('termination', '终止/废标公告'), ('contract', '合同公示'), ('acceptance', '验收公示'), ('result', '结果公告'), ('other', '其他公告')], default='bidding', max_length=20, verbose_name='公告类型')),
                ('region', models.CharField(choices=[('all', '全部'), ('beijing', '北京'), ('tianjin', '天津'), ('hebei', '河北'), ('shanxi', '山西'), ('neimenggu', '内蒙古'), ('liaoning', '辽宁'), ('jilin', '吉林'), ('heilongjiang', '黑龙江'), ('shanghai', '上海'), ('jiangsu', '江苏'), ('zhejiang', '浙江'), ('anhui', '安徽'), ('fujian', '福建'), ('jiangxi', '江西'), ('shandong', '山东'), ('henan', '河南'), ('hubei', '湖北'), ('hunan', '湖南'), ('guangdong', '广东'), ('guangxi', '广西'), ('hainan', '海南'), ('chongqing', '重庆'), ('sichuan', '四川'), ('guizhou', '贵州'), ('yunnan', '云南'), ('xizang', '西藏'), ('shaanxi', '陕西'), ('gansu', '甘肃'), ('qinghai', '青海'), ('ningxia', '宁夏'), ('xinjiang', '新疆')], default='all', max_length=20, verbose_name='地区')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='城市')),
                ('category', models.CharField(choices=[('university', '高校'), ('hospital', '医院'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('project_amount', models.CharField(blank=True, choices=[('below_10', '10万以下'), ('10_50', '10万到50万'), ('50_100', '50万到100万'), ('100_500', '100万到500万'), ('500_1000', '500万到1000万'), ('above_1000', '1000万以上')], max_length=20, verbose_name='项目金额')),
                ('procurement_category', models.CharField(blank=True, choices=[('goods', '货物类'), ('engineering', '工程类'), ('service', '服务类')], max_length=20, verbose_name='采购品目')),
                ('industry', models.CharField(choices=[('construction', '建筑工程'), ('water', '水利水电'), ('energy', '能源化工'), ('security', '弱电安防'), ('it', '信息技术'), ('office', '行政办公'), ('machinery', '机械设备'), ('transportation', '交通工程'), ('medical', '医疗卫生'), ('municipal', '市政设施'), ('service', '服务采购'), ('agriculture', '农林牧渔'), ('other', '其他')], default='other', max_length=20, verbose_name='所属行业')),
                ('project_number', models.CharField(blank=True, max_length=100, verbose_name='项目编号')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='发布单位')),
                ('content', wagtail.fields.RichTextField(verbose_name='公告内容')),
                ('attachment', models.FileField(blank=True, upload_to='announcements/attachments/', verbose_name='附件')),
            ],
            options={
                'verbose_name': '公告',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FavoriteAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.announcementpage', verbose_name='公告')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏的公告',
                'verbose_name_plural': '收藏的公告',
                'unique_together': {('user', 'announcement')},
            },
        ),
    ]
