# Generated by Django 6.0.2 on 2026-02-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementpage',
            name='purchase_amount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='采购金额（元）'),
        ),
        migrations.AddField(
            model_name='announcementpage',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, verbose_name='供应商名称'),
        ),
    ]
