# Generated by Django 6.0.2 on 2026-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcementpage_purchase_amount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementpage',
            name='purchase_amount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='采购金额（万元）'),
        ),
        migrations.AlterField(
            model_name='announcementpage',
            name='region',
            field=models.CharField(choices=[('all', '全部'), ('beijing', '北京'), ('tianjin', '天津'), ('hebei', '河北'), ('shanxi', '山西'), ('neimenggu', '内蒙古'), ('liaoning', '辽宁'), ('jilin', '吉林'), ('heilongjiang', '黑龙江'), ('shanghai', '上海'), ('jiangsu', '江苏'), ('zhejiang', '浙江'), ('anhui', '安徽'), ('fujian', '福建'), ('jiangxi', '江西'), ('shandong', '山东'), ('henan', '河南'), ('hubei', '湖北'), ('hunan', '湖南'), ('guangdong', '广东'), ('guangxi', '广西'), ('hainan', '海南'), ('chongqing', '重庆'), ('sichuan', '四川'), ('guizhou', '贵州'), ('yunnan', '云南'), ('xizang', '西藏'), ('shaanxi', '陕西'), ('gansu', '甘肃'), ('qinghai', '青海'), ('ningxia', '宁夏'), ('xinjiang', '新疆'), ('hongkong', '香港'), ('macau', '澳门'), ('taiwan', '台湾')], default='all', max_length=20, verbose_name='地区'),
        ),
    ]
