# Generated by Django 6.0.2 on 2026-02-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcementpage_purchase_amount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementpage',
            name='purchase_amount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='采购金额（元）'),
        ),
    ]
