# Generated by Django 6.0.2 on 2026-02-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcementpage_purchase_amount_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementpage',
            name='project_amount',
        ),
    ]
