# Generated by Django 6.0.2 on 2026-02-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_remove_announcementpage_project_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementpage',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='公告原文链接'),
        ),
    ]
