# Generated by Django 6.0.2 on 2026-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_announcementpage_external_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementpage',
            name='supplier',
        ),
        migrations.AddField(
            model_name='announcementpage',
            name='agency',
            field=models.CharField(blank=True, max_length=200, verbose_name='代理机构'),
        ),
    ]
