# Generated by Django 6.0.2 on 2026-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_remove_announcementpage_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementpage',
            name='category',
        ),
        migrations.AlterField(
            model_name='announcementpage',
            name='announcement_type',
            field=models.CharField(choices=[('winning_bid', '中标公告'), ('public_bidding', '公开招标公告'), ('competitive_negotiation', '竞争性谈判公告'), ('correction', '更正公告'), ('competitive_consultation', '竞争性磋商公告'), ('transaction', '成交公告'), ('other', '其他公告'), ('termination', '终止公告'), ('qualification', '资格预审公告'), ('inquiry', '询价公告')], default='public_bidding', max_length=30, verbose_name='公告类型'),
        ),
        migrations.AlterField(
            model_name='announcementpage',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, verbose_name='采购单位'),
        ),
    ]
