# Generated by Django 6.0.2 on 2026-02-11 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_remove_announcementpage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementpage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='发布日期'),
        ),
    ]
